const caseDatabase = [
    {
        case: "A.K. Gopalan vs State of Madras",
        year: 1950,
        bench: 6,
        judgement: "Held that detention is valid if it follows <span style='color: red;'>procedure established by law</span>; adopted a <span style='color: red;'>narrow interpretation of Article 21</span>.",
    },
    {
        case: "State of Madras vs Champakam Dorairajan",
        year: 1951,
        bench: 7,
        judgement: "<span style='color:red';>Fundamental Rights prevail over DPSP</span>. The Supreme Court struck down caste-based reservations in educational institutions under the Communal G.O. as <span style='color:red';>violative of Articles 15(1) and 29(2)</span> leads to 1st CA, 1951",
    },
    {
        case: "Shankari Prasad vs Union of India",
        year: 1951,
        bench: 5,
        judgement: "Parliament can amend Fundamental Rights under Article 368.",
    },
    {
        case: "In Re: The Kerala Education Bill",
        year: 1958,
        bench: 7,
        judgement: "The Supreme Court adopted the <span style='color: red;'>Doctrine of Harmonious Construction</span> and held that the <span style='color: red;'>Directive Principles of State Policy (DPSPs) cannot override Fundamental Rights</span>. Instead, both should be interpreted harmoniously so that effect can be given to each as far as possible.",
    },
    {
        case: "In Re: Berubari Union",
        year: 1960,
        bench: 8,
        judgement: "Transfer of Indian territory to another country requires a <span style='color:red';>constitutional amendment</span>.",
    },
    {
        case: "I.C. Golaknath vs State of Punjab",
        year: 1967,
        bench: 11,
        judgement: "Parliament <span style='color:red';>cannot amend Fundamental Rights</span> under Article 368.",
    },
    {
        case: "Kesavananda Bharati vs State of Kerala",
        year: 1973,
        bench: 13,
        judgement: "Introduced the <span style='color:red';>Basic Structure Doctrine</span>; Parliament cannot alter the Constitution's basic structure.",
    },
    {
        case: "Indira Gandhi vs Raj Narain",
        year: 1975,
        bench: 5,
        judgement: "Applied Basic Structure Doctrine i.e. <span style='color:orange';>Separation of Power</span>, <span style='color:yellow';>Free and Fair election</span> and <span style='color:blue';>Judicial Review</span> and struck down Article 329A(4) i.e. Elecion of PM and Speaker out of Judicial review",
    },
    {
        case: "Rev. Stainislaus vs State of Madhya Pradesh",
        year: 1977,
        bench: 5,
        judgement: "The Supreme Court held that the <span style='color: red;'>right to propagate religion</span> under <span style='color: red;'>Article 25</span> includes the right to spread and explain one's religious beliefs, but <span style='color: red;'>does not include the right to convert another person</span>.",

    },
    {
        case: "Maneka Gandhi vs Union of India",
        year: 1978,
        bench: 7,
        judgement: "Article 21 include the doctrine of <span style='color: red;'>Due Process of Law</span> by reading the presence of Principles of Natural Justice and linked <span style='color: red;'>Articles 14, 19 and 21</span> together as <span style='color: red;'>Golden Triange</span>.",
    },
    {
        case: "Minerva Mills Ltd. vs Union of India",
        year: 1980,
        bench: 5,
        judgement: "Parliament's amending power is limited by the Basic Structure Doctrine. <br> The changes introduced in Article 31C throught 42nd CA, 1976 were unconstitutional as it disturb the <span style='color:red';>Balance between FR and DPSP</span> which is itslef part of <span style='color: red';>Basic structre</span>.",
    },
    {
        case: "Waman Rao vs Union of India",
        year: 1981,
        bench: 5,
        judgement: "Ninth Schedule laws added <span style='color: red;'>after 24 April 1973</span> are subject to judicial review.",
    },
    {
        case: "Mohd. Ahmed Khan vs Shah Bano Begum",
        year: 1985,
        bench: 5,
        judgement: "A divorced Muslim woman is entitled to maintenance under CrPC.",
    },
    {
        case: "Olga Tellis vs Bombay Municipal Corporation",
        year: 1985,
        bench: 5,
        judgement: "Right to livelihood is an integral part of the Right to Life under Article 21.",
    },
    {
        case: "Indra Sawhney vs Union of India",
        year: 1992,
        bench: 9,
        judgement: "Upheld OBC reservation of 27%, excluded creamy layer and capped reservation at 50%.",
    },
    {
        case: "S.R. Bommai vs Union of India",
        year: 1994,
        bench: 9,
        judgement: "Restricted misuse of Article 356 and strengthened federalism.",
    },
    {
        case: "Sarla Mudgal vs Union of India",
        year: 1995,
        bench: 2,
        judgement: "Religious conversion cannot be used to evade bigamy laws.",
    },
    {
        case: "Vishaka vs State of Rajasthan",
        year: 1997,
        bench: 3,
        judgement: "Laid down <span style='color: red;'>Vishaka Guidelines</span> against workplace sexual harassment.",
    },
    {
        case: "D.K. Basu vs State of West Bengal",
        year: 1997,
        bench: 2,
        judgement: "Issued safeguards against custodial torture and illegal arrests.",
    },
    {
        case: "I.R. Coelho vs State of Tamil Nadu",
        year: 2007,
        bench: 9,
        judgement: "Ninth Schedule laws added after 24 April 1973 can be reviewed if they violate the Basic Structure.",
    },
    {
        case: "Aruna Shanbaug vs Union of India",
        year: 2011,
        bench: 2,
        judgement: "Recognized passive euthanasia under strict judicial safeguards.",
    },
    {
        case: "Lily Thomas vs Union of India",
        year: 2013,
        bench: 2,
        judgement: "Convicted MPs and MLAs lose membership immediately upon conviction.",
    },
    {
        case: "People's Union for Civil Liberties (PUCL) vs Union of India",
        year: 2013,
        bench: 3,
        judgement: "SC directed Election Commission to introduce <span style='color: red;'>None of the Above (NOTA)</span> option in EVMs and ballot papers. The Court held that the <span style='color: red;'>right to secrecy</span> and the <span style='color: red;'>right to express disapproval of all candidates</span> are part of the <span style='color: red;'>Freedom of Speech and Expression under Article 19(1)(a)</span>. ",
    },
    {
        case: "National Legal Services Authority vs Union of India",
        year: 2014,
        bench: 2,
        judgement: "Recognized transgender persons as the third gender and granted constitutional protections.",
    },
    {
        case: "Shreya Singhal vs Union of India",
        year: 2015,
        bench: 2,
        judgement: "The Supreme Court struck down <span style='color: red;'>Section 66A of the Information Technology Act, 2000</span> as unconstitutional, holding that it violated the <span style='color: red;'>Freedom of Speech and Expression under Article 19(1)(a)</span>.",
    },
    {
        case: "Justice K.S. Puttaswamy vs Union of India",
        year: 2017,
        bench: 9,
        judgement: "Declared Right to Privacy as a Fundamental Right.",
    },
    {
        case: "Shayara Bano vs Union of India",
        year: 2017,
        bench: 5,
        judgement: "Declared instant Triple Talaq unconstitutional.",
    },
    {
        case: "Navtej Singh Johar vs Union of India",
        year: 2018,
        bench: 5,
        judgement: "Decriminalized consensual homosexual relations by reading down Section 377 IPC.",
    },
    {
        case: "Anuradha Bhasin vs Union of India",
        year: 2020,
        bench: 3,
        judgement: "Internet access is integral to freedom of speech and trade; restrictions must be proportionate.",
    },
    {
        case: "Anoop Baranwal vs Union of India",
        year: 2023,
        bench: 5,
        judgement: "Directed appointment of Election Commissioners through a committee consisting of PM, LoP and CJI until Parliament enacts a law.",
    },
    {
        case: "Association for Democratic Reforms vs Union of India",
        year: 2024,
        bench: 5,
        judgement: "Struck down the Electoral Bonds Scheme as unconstitutional.",
    }
];
