const articles = [
    { id: "13(1)", text: "All the laws enforced in India immediately before commencement of the constitution shall be unconstitutional and void if they violate one or more provisions of Part 3 to the extent of violation.", amend: "" },
    { id: "13(2)", text: "After the commencement of Constitution, State shall not make any law that takes away or abridges one or more fundamental rights; if any such law is passed, then it shall be held unconstitutional and void to the extent of violation.", amend: "" },
    { id: "13(3)", text: "Definition of Law.", amend: "" },
    { id: "14", text: "The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.", amend: "" },
    { id: "15(1)", text: "State shall not discriminate against citizens only on ground of religion, race, caste, sex, place of birth or any of them.", amend: "" },
    { id: "15(2)", text: "It prohibits the state and individuals from discriminating against citizens only on the ground of religion, race, caste, sex, place of birth or any of them in having access to public places like parks, hotels, restaurants, hospitals, roads, tanks etc.", amend: "" },
    { id: "15(3)", text: "It enables the state to make special provisions for the welfare of women and children.", amend: "" },
    { id: "15(4)", text: "It empowers the state to make any special provisions for the advancement of socially and educationally backward classes of citizens or SCs/STs.", amend: "1, 1951" },
    { id: "15(5)", text: "It empowers the state to make special provisions for the admission of backward classes of citizens in educational institutions whether public or private, aided or unaided except minority educational institutions.", amend: "93, 2005" },
    { id: "15(6)", text: "It enables the state to provide for reservation up to 10% for economically weaker sections in educational institutions whether public or private, aided or unaided except minority educational institutions.", amend: "103, 2019" },
    { id: "16(1)", text: "It provides for equality of opportunities for all citizens in case of public employment.", amend: "" },
    { id: "16(2)", text: "It prohibits the state from discriminating against citizens only on grounds of religion, race, caste, sex, place of birth, residence, descent or any of them in having access to public employment.", amend: "" },
    { id: "16(3)", text: "Parliament is empowered to provide by law, residence as a ground or qualification in certain categories of public employment under the state.", amend: "" },
    { id: "16(4)", text: "It empowers the state to make special provisions in the favor of backward classes of citizens in reserving the posts of the nature of public employment if the backward class is not adequately represented in public services.", amend: "" },
    { id: "16(4A)", text: "It provides reservation in Promotion for SC and STs.", amend: "77, 1995" },
    { id: "16(5)", text: "It empowers the state to prescribe religion as a ground or qualification for recruitment of candidates in certain categories of public employment.", amend: "" },
    { id: "16(6)", text: "It enables the state to provide for reservation in public employment for economically weaker section up to 10%.", amend: "103, 2019" },
    { id: "17", text: "It abolishes untouchability in all the forms. (Untouchability Offences Act 1955 and Civil Rights Protection Act 1976)", amend: "" },
    { id: "18(1)", text: "Prohibits the state from conferring any title except in the form of military or academic achievement.", amend: "" },
    { id: "18(2)", text: "Prohibits the citizens of India from accepting any title from a foreign state.", amend: "" },
    { id: "18(3)", text: "A foreigner holding office of profit or trust under the Indian state can't accept a title from a foreign state without the permission of the Indian President.", amend: "" },
    { id: "18(4)", text: "No Person holding office of profit under Indian state shall accept any present/gift, emoluments or office under any foreign state without the permission of the president.", amend: "" },
    { id: "19(1)(a)", text: "Guarantees to all citizens a fundamental right to freedom of speech and expression.", amend: "" },
    { id: "19(2)", text: "Freedom of speech and expression are restricted on the grounds of Security and Sovereignty of India, friendly relations with other countries, public order, morality, decency, defamation, contempt of court etc.", amend: "" },
    { id: "19(1)(b)", text: "Guarantees right to assemble to all the citizens including right to hold meetings and carrying out processions, but in a peaceful manner.", amend: "" },
    { id: "19(1)(c)", text: "Guarantees right to form association, union or co-operative society.", amend: "" },
    { id: "19(1)(d)", text: "Guarantees right to move freely throughout the territory of India; no part of India shall be made inaccessible for Indian citizens. (Can be restricted for Security, Public order, or ST interests).", amend: "" },
    { id: "19(1)(e)", text: "Guarantees freedom of residence and settlement to the citizens of India in any part of India provided it doesn't affect general public or STs.", amend: "" },
    { id: "19(1)(f)", text: "Provided for Right to Property which was removed from Part 3 and introduced in Article 300A. It's now a constitutional or legal right.", amend: "44, 1978" },
    { id: "19(1)(g)", text: "Guarantees right to vocation/trade of one's choice. State can impose restrictions like qualifications or take over a business in public interest.", amend: "" },
    { id: "20(1)", text: "Prohibits ex post facto criminal legislation. No man shall be convicted for an act which was not a crime at the time of its commissioning, nor subjected to a greater penalty.", amend: "" },
    { id: "20(2)", text: "Prohibits double jeopardy: No Person shall be prosecuted and punished for the same offence in a court of law more than once.", amend: "" },
    { id: "20(3)", text: "Prohibits self-incrimination: No person can be forced to be a witness against himself.", amend: "" },
    { id: "21", text: "Guarantees right to life and personal liberty. No Person shall be deprived of his life or liberty except according to procedure established by law (PEBL/DPL).", amend: "" },
    { id: "21A", text: "State shall provide free and compulsory education to any children (Indian and Foreigner) age 6 to 14 years as provided by law.", amend: "86, 2002" },
    { id: "22(1)", text: "No person who is arrested shall be detained in custody without being informed in writing of the ground of his arrest.", amend: "" },
    { id: "22(2)", text: "The arrested person shall be produced before the nearest judicial magistrate within 24 hours of arrest excluding journey time.", amend: "" },
    { id: "22(3)", text: "No person shall be detained in custody beyond the period which was authorized by the magistrate.", amend: "" },
    { id: "23(1)", text: "Prohibits traffic in human beings, begar or any other form of forced labour.", amend: "" },
    { id: "23(2)", text: "Empowers state to force the individual to provide service with or without payment provided it's in public interest.", amend: "" },
    { id: "24", text: "Prohibits employment of Children below age 14 years in hazardous employment.", amend: "" },
    { id: "25", text: "Guarantees freedom of conscience and the right to freely profess, practice and propagate a religion of one's choice.", amend: "" },
    { id: "26", text: "Freedom of religious denominations to manage religious affairs, own property, and maintain religious/charitable institutions.", amend: "" },
    { id: "27", text: "Prohibits the state from spending tax collections for the promotion and maintenance of any particular religious denomination.", amend: "" },
    { id: "28(1)", text: "In Educational Institutions completely owned and administered by State, no religious instructions whatsoever can be imparted.", amend: "" },
    { id: "28(2)", text: "In Private Educational Institutions (aided/unaided), religious instructions can be imparted but students can't be forced to attend.", amend: "" },
    { id: "28(3)", text: "In Educational Institutions administered by State but established through religious endowment, religious instructions can be made compulsory.", amend: "" },
    { id: "29(1)", text: "Any section of citizens residing in India having a distinct language, script or culture have a right to conserve the same.", amend: "" },
    { id: "29(2)", text: "No citizen shall be denied admission in educational institutions maintained by state or receiving state aid only on ground of religion, race, caste, or language.", amend: "" },
    { id: "30(1)", text: "All minorities whether based on religion or language have a right to establish and administer educational institutions of their choice.", amend: "" },
    { id: "32(1)", text: "Confers the power on Supreme Court to issue appropriate orders, directions or writs to enforce fundamental rights.", amend: "" },
    { id: "32(2)", text: "Writ jurisdiction of Supreme Court: Power to issue writs.", amend: "" },
    { id: "32(3)", text: "Parliament has the power to confer writ jurisdiction by means of law on any other body.", amend: "" }
];
